#ifndef DANAMICDATADRIVELIB_GLOBAL_H
#define DANAMICDATADRIVELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DANAMICDATADRIVELIB_LIBRARY)
#  define DANAMICDATADRIVELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DANAMICDATADRIVELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DANAMICDATADRIVELIB_GLOBAL_H
